accueil/urls.py
from django.urls import path
from accueil import views

app_name="accueil"
urlpatterns = [
    path('index/', views.index, name='index'),
    
]

parametre/urls.py
from django.contrib.auth import views as djviews
from django.urls import path
from parametre.forms import LoginForm
from parametre import views


context={'fichier_page_accueil': 'fichier_page_accueil.png'}

app_name="parametre"
urlpatterns = [
    path('index/', views.index, name='index'),

    path('tarification/', views.tarification, name='tarification'),
    path('composition_detail/', views.composition_detail, name='composition_detail'),
    path('composition/', views.composition, name='composition'),
    path('produit_emballage/', views.produit_emballage, name='produit_emballage'),
    path('emballage/', views.emballage, name='emballage'),
    path('produit/', views.produit, name='produit'),
    path('type_produit/', views.type_produit, name='type_produit'),
    path('fournisseur/', views.fournisseur, name='fournisseur'),
    path('machine/', views.machine, name='machine'),
    path('site/', views.site, name='site'),
    path('constructeur/', views.constructeur, name='constructeur'),

    path('commune/', views.commune, name='commune'),
    path('ville/', views.ville, name='ville'),
    path('departement/', views.departement, name='departement'),
    path('region/', views.region, name='region'),    
    path('pays/', views.pays, name='pays'),
    path('continent/', views.continent, name='continent'),
    path('societe/', views.societe, name='societe'),    

    path('login/', djviews.LoginView.as_view(template_name= 'login.html', authentication_form= LoginForm), name='login'),
    path('logout/', djviews.LogoutView.as_view(next_page='parametre:login')), 
]

village/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

parametre/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.forms import ModelForm, inlineformset_factory, formset_factory, modelformset_factory
from django.contrib.admin.widgets import AdminDateWidget
#from django.forms import widgets
from django.contrib.auth.forms import AuthenticationForm 
from django.forms.widgets import RadioSelect, CheckboxSelectMultiple
from bootstrap_datepicker_plus.widgets import DatePickerInput

from django.urls import reverse_lazy
from django_addanother.widgets import AddAnotherWidgetWrapper, AddAnotherEditSelectedWidgetWrapper

from parametre.models import *
from datetime import date, timedelta


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="User name", max_length=30, 
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30, 
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))


class SocieteForm(ModelForm):
	class Meta:
		model=Societe
		fields= '__all__'


class ContratForm(ModelForm):
    class Meta:
      model = Contrat
      exclude=("etatContrat",)


class ContactForm(forms.ModelForm):
    class Meta:
      model = Contact
      fields = "__all__"
   

class ClotureForm(ModelForm):
    exercice = forms.ModelChoiceField(empty_label=None, queryset = Exercice.objects.order_by('-annee'))
    class Meta:
        model = Cloture
        exclude = ()
        widgets = {
           'date_cloture' : DatePickerInput(options={
                          'format': 'DD/MM/YYYY',
                          'locale': "fr",
                          }),
    }

parametre/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.forms import modelformset_factory

from parametre.models import * 
from .forms import SocieteForm


@login_required(login_url="login/")
def index(request):
	return render(request, 'parametre/index.html')


def tarification(request):
    return 

def fournisseur(request):
    fournisseurFormSet = modelformset_factory(Fournisseur, extra=3, exclude=())
    formset = fournisseurFormSet(queryset=Fournisseur.objects.order_by('nom'))
    for form in formset:
        for field in form.fields:form.fields[field].label='' 
    if request.method=='POST':
        formset = fournisseurFormSet(request.POST)
        if formset.is_valid():
            for i in filter(lambda x : (x.is_valid() and x.has_changed() and x.cleaned_data['nom']), formset):
                i.save()
            formset = fournisseurFormSet(queryset=Fournisseur.objects.order_by('nom'))
            for form in formset:
                for field in form.fields:form.fields[field].label='' 
            return render(request, 'parametre/fournisseur.html', locals())
    return render(request, 'parametre/fournisseur.html', locals())

def composition_detail(request):
    detail_compositionFormSet = modelformset_factory(Detailscomposition, extra=3, exclude=())
    formset = detail_compositionFormSet(queryset=Detailscomposition.objects.order_by('produit'))
    for form in formset:
        for field in form.fields:form.fields[field].label='' 
    if request.method=='POST':
        formset = detail_compositionFormSet(request.POST)
        if formset.is_valid():
            for i in filter(lambda x : (x.is_valid() and x.has_changed() and x.cleaned_data['produit']), formset):
                i.save()
            formset = detail_compositionFormSet(queryset=Detailscomposition.objects.order_by('produit'))
            for form in formset:
                for field in form.fields:form.fields[field].label='' 
            return render(request, 'parametre/composition_detail.html', locals())
    return render(request, 'parametre/composition_detail.html', locals())


def composition(request):
    compositionFormSet = modelformset_factory(Composition, extra=3, exclude=())
    formset = compositionFormSet(queryset=Composition.objects.order_by('libelle'))
    for form in formset:
        for field in form.fields:form.fields[field].label='' 
    if request.method=='POST':
        formset = compositionFormSet(request.POST)
        if formset.is_valid():
            for i in filter(lambda x : (x.is_valid() and x.has_changed() and x.cleaned_data['libelle']), formset):
                i.save()
            formset = compositionFormSet(queryset=Composition.objects.order_by('libelle'))
            for form in formset:
                for field in form.fields:form.fields[field].label='' 
            return render(request, 'parametre/composition.html', locals())
    return render(request, 'parametre/composition.html', locals())


def produit_emballage(request):
    produit_emballageFormSet = modelformset_factory(ProduitEmballage, extra=3, exclude=())
    formset = produit_emballageFormSet(queryset=ProduitEmballage.objects.order_by('produit'))
    for form in formset:
        for field in form.fields:form.fields[field].label='' 
    if request.method=='POST':
        formset = produit_emballageFormSet(request.POST)
        if formset.is_valid():
            for i in filter(lambda x : (x.is_valid() and x.has_changed() and x.cleaned_data['produit']), formset):
                i.save()
            formset = produit_emballageFormSet(queryset=ProduitEmballage.objects.order_by('produit'))
            for form in formset:
                for field in form.fields:form.fields[field].label='' 
            return render(request, 'parametre/produit_emballage.html', locals())
    return render(request, 'parametre/produit_emballage.html', locals())


def emballage(request):
    emballageFormSet = modelformset_factory(Emballage, extra=3, exclude=())
    formset = emballageFormSet(queryset=Emballage.objects.order_by('libelle'))
    for form in formset:
        for field in form.fields:form.fields[field].label='' 
    if request.method=='POST':
        formset = emballageFormSet(request.POST)
        if formset.is_valid():
            for i in filter(lambda x : (x.is_valid() and x.has_changed() and x.cleaned_data['libelle']), formset):
                i.save()
            formset = emballageFormSet(queryset=Emballage.objects.order_by('libelle'))
            for form in formset:
                for field in form.fields:form.fields[field].label='' 
            return render(request, 'parametre/emballage.html', locals())
    return render(request, 'parametre/emballage.html', locals())


def produit(request):
    produitFormSet = modelformset_factory(Produit, extra=3, exclude=())
    formset = produitFormSet(queryset=Produit.objects.order_by('libelle'))
    for form in formset:
        for field in form.fields:form.fields[field].label='' 
    if request.method=='POST':
        formset = produitFormSet(request.POST)
        if formset.is_valid():
            for i in filter(lambda x : (x.is_valid() and x.has_changed() and x.cleaned_data['libelle']), formset):
                i.save()
            formset = produitFormSet(queryset=Produit.objects.order_by('libelle'))
            for form in formset:
                for field in form.fields:form.fields[field].label='' 
            return render(request, 'parametre/produit.html', locals())
    return render(request, 'parametre/produit.html', locals())


def type_produit(request):
    type_produitFormSet = modelformset_factory(TypeProduit, extra=3, exclude=())
    formset = type_produitFormSet(queryset=TypeProduit.objects.order_by('libelle'))
    for form in formset:
        for field in form.fields:form.fields[field].label='' 
    if request.method=='POST':
        formset = type_produitFormSet(request.POST)
        if formset.is_valid():
            for i in filter(lambda x : (x.is_valid() and x.has_changed() and x.cleaned_data['libelle']), formset):
                i.save()
            formset = type_produitFormSet(queryset=TypeProduit.objects.order_by('libelle'))
            for form in formset:
                for field in form.fields:form.fields[field].label='' 
            return render(request, 'parametre/type_produit.html', locals())
    return render(request, 'parametre/type_produit.html', locals())


def machine(request):
    machineFormSet = modelformset_factory(Machine, extra=3, exclude=())
    formset = machineFormSet(queryset=Machine.objects.order_by('libelle'))
    for form in formset:
        for field in form.fields:form.fields[field].label='' 
    if request.method=='POST':
        formset = machineFormSet(request.POST)
        if formset.is_valid():
            for i in filter(lambda x : (x.is_valid() and x.has_changed() and x.cleaned_data['libelle']), formset):
                i.save()
            formset = machineFormSet(queryset=Machine.objects.order_by('libelle'))
            for form in formset:
                for field in form.fields:form.fields[field].label='' 
            return render(request, 'parametre/machine.html', locals())
    return render(request, 'parametre/machine.html', locals())


def site(request):
    siteFormSet = modelformset_factory(Site, extra=3, exclude=())
    formset = siteFormSet(queryset=Site.objects.order_by('libelle'))
    for form in formset:
        for field in form.fields:form.fields[field].label='' 
    if request.method=='POST':
        formset = siteFormSet(request.POST)
        if formset.is_valid():
            for i in filter(lambda x : (x.is_valid() and x.has_changed() and x.cleaned_data['libelle']), formset):
                i.save()
            formset = siteFormSet(queryset=Site.objects.order_by('libelle'))
            for form in formset:
                for field in form.fields:form.fields[field].label='' 
            return render(request, 'parametre/site.html', locals())
    return render(request, 'parametre/site.html', locals())



def constructeur(request):
    constructeurFormSet = modelformset_factory(Constructeur, extra=3, exclude=())
    formset = constructeurFormSet(queryset=Constructeur.objects.order_by('libelle'))
    for form in formset:
        for field in form.fields:form.fields[field].label='' 
    if request.method=='POST':
        formset = constructeurFormSet(request.POST)
        if formset.is_valid():
            for i in filter(lambda x : (x.is_valid() and x.has_changed() and x.cleaned_data['libelle']), formset):
                i.save()
            formset = constructeurFormSet(queryset=Constructeur.objects.order_by('libelle'))
            for form in formset:
                for field in form.fields:form.fields[field].label='' 
            return render(request, 'parametre/constructeur.html', locals())
    return render(request, 'parametre/constructeur.html', locals())


def pays(request):
    paysFormSet = modelformset_factory(Pays, extra=3, exclude=())
    formset = paysFormSet(queryset=Pays.objects.order_by('libelle'))
    for form in formset:
        for field in form.fields:form.fields[field].label='' 
    if request.method=='POST':
        formset = paysFormSet(request.POST)
        if formset.is_valid():
            for i in filter(lambda x : (x.is_valid() and x.has_changed() and x.cleaned_data['libelle']), formset):
                i.save()
            formset = paysFormSet(queryset=Pays.objects.order_by('libelle'))
            for form in formset:
                for field in form.fields:form.fields[field].label='' 
            return render(request, 'parametre/pays.html', locals())
    return render(request, 'parametre/pays.html', locals())


def region(request):
    regionFormSet = modelformset_factory(Region, extra=3, exclude=())

parametre/templates/parametre/aside.html
{% load static %}
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{{ MEDIA_URL }}{{ user.profil.photo.url }}" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>{{ user.last_name }}</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    <p><small>{{ user.profil.fonction }}</small></p>
                </div>
            </div>
            <!-- search form -->
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header" style="color:orange"><center><h4> PARAMETRES</h4></center></li>
                

                {% comment %}
                <li>
                    <a href="{#% url 'reservation:reservation' %#}">
                        <i class="fa fa-envelope"></i> <span>Reservations</span>
                        <span class="pull-right-container">
                            <small class="label pull-right bg-yellow">12</small>
                            <small class="label pull-right bg-green">16</small>
                            <small class="label pull-right bg-red">5</small>
                        </span>
                    </a>
                </li>

                <li>
                    <a href="{#% url 'occupation:passage' %#}">
                        <i class="fa fa-envelope"></i> <span>Passages</span>
                        <span class="pull-right-container">
                            <small class="label pull-right bg-yellow">12</small>
                            <small class="label pull-right bg-green">16</small>
                            <small class="label pull-right bg-red">5</small>
                        </span>
                    </a>
                </li>

                <li>
                    <a href="{#% url 'occupation:sejour' %#}">
                        <i class="fa fa-envelope"></i> <span>Séjours</span>
                        <span class="pull-right-container">
                            <small class="label pull-right bg-yellow">12</small>
                            <small class="label pull-right bg-green">16</small>
                            <small class="label pull-right bg-red">5</small>
                        </span>
                    </a>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-pie-chart"></i>
                        <span>Facturation</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{#% url 'facturation:reglement' %#}"><i class="fa fa-circle-o"></i> Règlements</a></li>
                        <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Personnels</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-pie-chart"></i>
                        <span>Paramètres</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{#% url 'parametre:chambre' %#}"><i class="fa fa-circle-o"></i> Chambres</a></li>
                    </ul>
                </li>

                <li>
                    <a href="{#% url 'planning:chambre' %#}">
                        <i class="fa fa-envelope"></i> <span>Chambres</span>
                        <span class="pull-right-container">
                            <small class="label pull-right bg-yellow">12</small>
                            <small class="label pull-right bg-green">16</small>
                            <small class="label pull-right bg-red">5</small>
                        </span>
                    </a>
                </li>
                {% endcomment %}
                
                <li>
                    <a href="{% url 'parametre:composition_detail' %}">
                        <i class="fa fa-envelope"></i> <span> Compositions des Menus</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'parametre:composition' %}">
                        <i class="fa fa-envelope"></i> <span> Menu des cafés proposés</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'parametre:produit_emballage' %}">
                        <i class="fa fa-envelope"></i> <span> Produits emballés</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>                
                <li>
                    <a href="{% url 'parametre:emballage' %}">
                        <i class="fa fa-envelope"></i> <span> Emballages</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'parametre:produit' %}">
                        <i class="fa fa-envelope"></i> <span> Produits</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>
               <li>
                    <a href="{% url 'parametre:type_produit' %}">
                        <i class="fa fa-envelope"></i> <span> Types de Produits</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'parametre:fournisseur' %}">
                        <i class="fa fa-envelope"></i> <span> Fournisseurs</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>                
                <li>
                    <a href="{% url 'parametre:machine' %}">
                        <i class="fa fa-envelope"></i> <span> Machines</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'parametre:site' %}">
                        <i class="fa fa-envelope"></i> <span> Sites</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'parametre:constructeur' %}">
                        <i class="fa fa-envelope"></i> <span> Constructeurs</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'parametre:commune' %}">
                        <i class="fa fa-envelope"></i> <span> Commune</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'parametre:ville' %}">
                        <i class="fa fa-envelope"></i> <span> Ville</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>            
                <li>
                    <a href="{% url 'parametre:departement' %}">
                        <i class="fa fa-envelope"></i> <span> Département</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'parametre:region' %}">
                        <i class="fa fa-envelope"></i> <span> Région</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'parametre:pays' %}">
                        <i class="fa fa-envelope"></i> <span> Pays</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'parametre:continent' %}">
                        <i class="fa fa-envelope"></i> <span> Continent</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'parametre:societe' %}">
                        <i class="fa fa-envelope"></i> <span> Société</span>
                        <span class="pull-right-container">
                        </span>
                    </a>
                </li>

            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

parametre/templates/parametre/composition.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% load crispy_forms_tags %}

{% block aside %}
  {% include 'parametre/aside.html' %}
{% endblock aside %} 

{% block content %}    
<section class="content-header">
  <h1>Menu des cafés proposés</h1>
  <ol class="breadcrumb">
    <a href="{% url 'parametre:index' %}"><span class="btn btn-xs btn-primary">Accueil</span></a>
   </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title"><span class="label label-primary"> Liste des menus<span class="badge">{{ formset|length|sub:3 }}</span></span></h3>
        </div>
       <div class="box-body">  
       <form class="form" method="post" action="{% url 'parametre:composition' %}"> {% csrf_token %} 
        {{ formset.non_form_errors.as_ul }}
          {{ formset.management_form }}
           <table id="table1" class="table table-bordered table-striped" cellspacing="10" style="width:100%">
              {% for form in formset.forms %}
                {% if forloop.first %}
                <thead><tr bgcolor="#bee5eb">
                <thead><tr bgcolor="#bee5eb">
                  <th>Libellé</th>
                  <th>Abrégé</th>
                </tr></thead>
                {% endif %}
                <tr class="{% cycle 'row1' 'row2' %}">
                {% for field in form.visible_fields %}
                  <td>
                  {# Include the hidden fields in the form #}
                  {% if forloop.first %}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                  {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                  </td>
                {% endfor %}
                </tr>
              {% endfor %}
            </table>

           <button class="btn btn-primary" type="submit" name="submit" value = "enregistrer">Enregistrer</button>
          </form>
        </div> 
        </div> 
     </div>
  </div>
</section>  


<style type="text/css">
  th, td {
    white-space: nowrap;
}
</style>

<script>
  $(function () {
    $('#table1').DataTable({
      'paging'      : false,
      'lengthChange': true,
      "lengthMenu"  : [[20, -1], [20, "All"]],
      'searching'   : false,
      'ordering'    : false,
      'info'        : false,
      'autoWidth'   : true,
      'scrollY'     : 400,
      'scrollCollapse' : true,
    })
  })
</script>
{% endblock %}

parametre/templates/parametre/composition_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% load crispy_forms_tags %}

{% block aside %}
  {% include 'parametre/aside.html' %}
{% endblock aside %}

{% block content %}    
<section class="content-header">
  <h1>Compositions des menus</h1>
  <ol class="breadcrumb">
    <a href="{% url 'parametre:index' %}"><span class="btn btn-xs btn-primary">Accueil</span></a>
   </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title"><span class="label label-primary">Liste des compositions des menus<span class="badge">{{ formset|length|sub:3 }}</span></span></h3>
        </div>
       <div class="box-body">  
       <form class="form" method="post" action="{% url 'parametre:composition_detail' %}"> {% csrf_token %} 
        {{ formset.non_form_errors.as_ul }}
          {{ formset.management_form }}
           <table id="table1" class="table table-bordered table-striped" cellspacing="10" style="width:100%">
              {% for form in formset.forms %}
                {% if forloop.first %}
                  <thead>
                    <tr bgcolor="#bee5eb">
                      <th>Menu</th>
                      <th>Produits</th>
                      <th>Quantité (g)</th>
                      <th>Observation</th> 
                    </tr>
                  </thead>
                {% endif %}
                <tr class="{% cycle 'row1' 'row2' %}">
                {% for field in form.visible_fields %}
                  <td>
                  {# Include the hidden fields in the form #}
                  {% if forloop.first %}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                  {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                  </td>
                {% endfor %}
                </tr>
              {% endfor %}
            </table>
           <button class="btn btn-primary" type="submit" name="submit" value = "enregistrer">Enregistrer</button>
          </form>
        </div> 
        </div> 
     </div>
  </div>
</section>  

<style type="text/css">
  th, td {
    white-space: nowrap;
}
</style>

<script>
  $(function () {
    $('#table1').DataTable({
      'paging'      : false,
      'lengthChange': true,
      "lengthMenu"  : [[20, -1], [20, "All"]],
      'searching'   : false,
      'ordering'    : false,
      'info'        : false,
      'autoWidth'   : true,
      'scrollY'     : 400,
      'scrollCollapse' : true,
    })
  })
</script>
{% endblock %}

parametre/templates/parametre/continent.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% load crispy_forms_tags %}

{% block aside %}
  {% include 'parametre/aside.html' %}
{% endblock aside %}


{% block content %}    
<section class="content-header">
  <h1>Continents</h1>
  <ol class="breadcrumb">
    <a href="{% url 'parametre:index' %}"><span class="btn btn-xs btn-primary">Accueil</span></a>
   </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title"><span class="label label-primary">Liste des continents <span class="badge">{{ formset|length|sub:3 }}</span></span></h3>
        </div>
       <div class="box-body">  
       <form class="form" id="signup_form" method="post" action="{% url 'parametre:continent' %}"> {% csrf_token %} 
        {{ formset.non_form_errors.as_ul }}
          {{ formset.management_form }}
           <table id="table1" class="table table-bordered table-striped" cellspacing="10" style="width:100%">
              {% for form in formset.forms %}
                {% if forloop.first %}
                <thead>
                  <tr bgcolor="#bee5eb">
                    <th>Continent</th>
                    <th>Abrégé</th>
                  </tr>
                </thead>
                {% endif %}
                <tr class="{% cycle 'row1' 'row2' %}">
                {% for field in form.visible_fields %}
                  <td>
                  {# Include the hidden fields in the form #}
                  {% if forloop.first %}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                  {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                  </td>
                {% endfor %}
                </tr>
              {% endfor %}
            </table>

           <button class="btn btn-primary" type="submit" name="submit" value = "enregistrer">Enregistrer</button>
          </form>
        </div> 
      </div> 
    </div>
  </div>
</section>  


<style type="text/css">
  th, td {
    white-space: nowrap;
}
</style>

<script>
  $(function () {
    $('#table1').DataTable({
      'paging'      : false,
      'lengthChange': true,
      "lengthMenu"  : [[20, -1], [20, "All"]],
      'searching'   : false,
      'ordering'    : false,
      'info'        : false,
      'autoWidth'   : true,
      'scrollY'     : 400,
      'scrollCollapse' : true,
    })
  })
</script>
{% endblock %}