accueil/urls.py
from django.urls import path
from accueil import views

app_name="accueil"
urlpatterns = [
    path('index/', views.index, name='index'),
    
]

parametre/urls.py
from django.contrib.auth import views as djviews
from django.urls import path
from parametre.forms import LoginForm
from parametre import views


context={'fichier_page_accueil': 'fichier_page_accueil.png'}

app_name="parametre"
urlpatterns = [
    path('index/', views.index, name='index'),

    path('tarification/', views.tarification, name='tarification'),
    path('composition_detail/', views.composition_detail, name='composition_detail'),
    path('composition/', views.composition, name='composition'),
    path('produit_emballage/', views.produit_emballage, name='produit_emballage'),
    path('emballage/', views.emballage, name='emballage'),
    path('produit/', views.produit, name='produit'),
    path('type_produit/', views.type_produit, name='type_produit'),
    path('fournisseur/', views.fournisseur, name='fournisseur'),
    path('machine/', views.machine, name='machine'),
    path('site/', views.site, name='site'),
    path('constructeur/', views.constructeur, name='constructeur'),

    path('commune/', views.commune, name='commune'),
    path('ville/', views.ville, name='ville'),
    path('departement/', views.departement, name='departement'),
    path('region/', views.region, name='region'),    
    path('pays/', views.pays, name='pays'),
    path('continent/', views.continent, name='continent'),
    path('societe/', views.societe, name='societe'),    

    path('login/', djviews.LoginView.as_view(template_name= 'login.html', authentication_form= LoginForm), name='login'),
    path('logout/', djviews.LogoutView.as_view(next_page='parametre:login')), 
]

village/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/aside.html
{% load static %}
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                {% if user.profil.photo %}
                    <img src="{{ MEDIA_URL }}{{ user.profil.photo.url }}" class="img-circle" alt="User Image">
                {% endif %}
            </div>
            <div class="pull-left info">
                <p>{{ user.last_name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                {% if user.profil.fonction %}
                <p><small>{{ user.profil.fonction }}</small></p>
                {% endif %}
            </div>
        </div>
        <!-- search form -->
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header" style="color:orange"><center><h4> ACCUEIL</h4></center></li>

            <li>
                <a href="{#% url 'tableaubord:index' %#}">
                    <i class="fa fa-dashboard"></i> <span> Tableau de bord</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'adresse:afficher_list' %#}">
                    <i class="fa fa-car"></i> <span> Parc Autos</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
            <li>
                <a href="{#% url 'stock:index' %#}">
                    <i class="fa fa-envelope teal-color"></i> <span> Stocks</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>

            <li>
                <a href="{% url 'parametre:index' %}">
                    <i class="fa fa-settings teal-color"></i> <span> Paramètres</span>
                    <span class="pull-right-container">
                    </span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->


    <style>
    .blue-color {
        color:blue;
    }
     
    .green-color {
        color:green;
    }
     
    .teal-color {
        color:teal;
    }
     
    .yellow-color {
    color:yellow;
    }
    
    .red-color {
        color:red;
    }
   </style>
</aside>

templates/base.html
<!DOCTYPE>
{% load static %}

<html  xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
  <head>
    <title>{{ societe.html_titre }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
       <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{% static 'css/jquery-jvectormap.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dataTables.checkboxes.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/buttons.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/datatables_select_dataTables.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
   </head>

   <body class="hold-transition skin-green-light sidebar-mini">
    <div class="wrapper">
      {% block header %}
        {% include "header.html" %}
      {% endblock header %}

      {% block aside %}
        {% include "aside.html" %}
      {% endblock aside %}
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        {% block content %}
        {% endblock content %}
      </div>
      {% block footer %}
        {% include "footer.html" %}
      {% endblock footer %}
      
      {% block sidebar %}
      {% endblock sidebar %}
    </div>
    <script>$.widget.bridge('uibutton', $.ui.button);</script>
      <script src="{% static 'js/jquery.min.js' %}"></script>
      
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <!-- DataTables -->
      <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>

      <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>
      <!-- AdminLTE App -->
      <script src="{% static 'js/adminlte.min.js' %}"></script>

      <script type="text/javascript" src="{% static 'js/dataTables.checkboxes.min.js' %}"></script>
      <!-- DataTables 
      <script src="{% static 'js/pdfmake.min.js' %}"></script>-->
      <script src="{% static 'js/vfs_fonts.js' %}"></script>
      <script src="{% static 'js/buttons.html5.min.js' %}"></script>
      <script src="{% static 'js/buttons.print.min.js' %}"></script>
      <script src="{% static 'js/dataTables.buttons.min.js' %}"></script>
      <script src="{% static 'js/dataTables.select.min.js' %}"></script>
      <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
  </body>
</html>

templates/footer.html
{% load static %}

<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.4.0
  </div>
    <strong>Copyright &copy; 2014-2016 <a href="#"> MOYENS GENERAUX</a>.</strong> All rights
    reserved.
</footer>

templates/header.html
{% load static %}
<header class="main-header">
  <!-- Logo -->
  <a href="{% url 'accueil:index' %}" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>{{ societe.html_societe_court }}</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><h5>{{ societe.html_societe_long }}</h5></span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
     	<!-- Collect the nav links, forms, and other content for toggling -->
    
    <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">APPLICATIONS <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            {% comment %}
            <li><a href="{% url 'tableaubord:index' %}"><i class="fa fa-user" style="color:orange"></i> Tableau de bord</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'reglement:index' %}"><i class="fa fa-user" style="color:orange"></i> Règlements clients</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'reglement:paiement_list' %}"><i class="fa fa-user" style="color:orange"></i> Règlements fournisseurs</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'reglement:caisse_list' %}"><i class="fa fa-user" style="color:orange"></i> Opérations de caisse</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'facturation:index' %}"><i class="fa fa-user" style="color:orange"></i>Facturation</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'achat:index' %}"><i class="fa fa-user" style="color:orange"></i> Appros</a></li>
            <li role="separator" class="divider"></li>
            {% endcomment %}
            <li><a href="{% url 'parametre:index' %}"><i class="fa fa-user" style="color:orange"></i> Paramétrage</a></li>
            <li role="separator" class="divider"></li>
            
            <li><a href="{% url 'parametre:login' %}"><i class="fa fa-user" style="color:orange"></i>Déconnexion</a></li>
          </ul>
        </li>  
      </ul>  
    </div>    
      
    <div class="collapse navbar-collapse pull-right" id="navbar-collapse">
      <ul class="nav navbar-nav">

        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            {% if user.profil.photo %}
            <img src="{{ MEDIA_URL }}{{ user.profil.photo.url }}" class="user-image" alt="User Image">
            {% endif %}
            <span class="hidden-xs">{{ user.last_name }}</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              {% if user.profil.photo %}
              <img src="{{ MEDIA_URL }}{{ user.profil.photo.url }}" class="img-circle" alt="User Image">
              {% endif %}
              <p>{{ user.last_name }} - {{ user.profil.fonction }}<small></small></p>
            </li>
          </ul>
        </li>

        <li class="dropdown">
          <li><a href="{% url 'accueil:index' %}">ACCUEIL</a></li>
          <li><a href="{% url 'parametre:login' %}">LOGOUT</a></li>
        </li>
  		</ul>
	  </div>

	</nav>
</header>

templates/login.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Job | Time</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!--  Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static "fondecran.css" %}">-->
  </head>

  <body>
     <!-- Main content -->
      <section class="content">
        <!-- Info boxes -->
          <div class="row">
              <div class="box-body">
                  <form method="post" action="{% url 'parametre:login' %}">{% csrf_token %}
                      <div class="col-md-4 col-md-offset-4">
                          <div class="form-group">
                              <table class="table table-bordered">
                                  <tr>
                                    <td>{{ form.username.label_tag }}</td>
                                    <td>{{ form.username }}</td>
                                  </tr>
                                  <tr>
                                    <td>{{ form.password.label_tag }}</td>
                                    <td>{{ form.password }}</td>
                                  </tr>
                              </table>
                              <p class="bs-component">
                                <button type="submit" class="btn btn-primary btn-block btn-flat">Login</button>
                              </p>
                                <input type="hidden" name="next" value="{{ next }}" />
                          </div>
                        </div>
                  </form>
              </div>
          </div>
          <center><img width="80%" height="400" src="{% static 'img/fichier_page_accueil.png' %}"></
      </section>
    </body>
</html>